

platform :ios, '13.0'

target 'HMSKitExample' do
  # pod 'HMSVideo'#, :path => '../'
  pod 'HMSKit', :git => 'https://github.com/100mslive/100ms-ios.git', :branch => 'usingSDK2.0'
  
  pod 'Firebase/Crashlytics'
  pod 'Firebase/AppDistribution'
  pod 'JWT'

  target 'HMSKitExampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
